# See the documentation for more information:
# https://packit.dev/docs/configuration/
upstream_package_name: mutter
downstream_package_name: mutter
upstream_project_url: https://gitlab.gnome.org/verdre/mutter-mobile
issue_repository: https://gitlab.gnome.org/verdre/mutter-mobile
srpm_build_deps:
  - meson
packages:
  gnome-48-mobile:
    actions:
      get-current-version: echo 48^mobile
      create-archive: &archive
        # Create archive
        - meson subprojects download
        - bash -c 'tar -zvcf .packit_rpm/${PACKIT_PROJECT_NAME_VERSION}.tar.gz --exclude "*.rpm" --exclude .packit_rpm --exclude .git --transform "s|^|${PACKIT_PROJECT_NAME_VERSION}/|" .'
        - bash -c 'echo ".packit_rpm/${PACKIT_PROJECT_NAME_VERSION}.tar.gz"'
      post-upstream-clone:
        # Use the Fedora 42 specfile
        - rm -rf .packit_rpm
        - git clone https://src.fedoraproject.org/rpms/mutter .packit_rpm --branch f42 --depth=1
        # Fix build deps
        - "sed -i 's/^BuildRequires: pkgconfig(gnome-settings-daemon)/BuildRequires: gnome-settings-daemon-devel = 48^mobile/' .packit_rpm/mutter.spec"
        - "sed -i 's/^Requires: gnome-settings-daemon/Requires: gnome-settings-daemon = 48^mobile/' .packit_rpm/mutter.spec"
        - rm -fv .packit_rpm/sources
    specfile_path: .packit_rpm/mutter.spec
  mobile-devel:
    actions:
      get-current-version: echo 48^mobile-devel
      create-archive: *archive
      post-upstream-clone:
        # Use the Fedora Rawhide specfile
        - rm -rf .packit_rpm
        - git clone https://src.fedoraproject.org/rpms/mutter .packit_rpm --branch rawhide --depth=1
        # Fix build deps
        - "sed -i 's/^BuildRequires: pkgconfig(gnome-settings-daemon)/BuildRequires: gnome-settings-daemon-devel = 48^mobile.devel/' .packit_rpm/mutter.spec"
        - "sed -i 's/^Requires: gnome-settings-daemon/Requires: gnome-settings-daemon = 48^mobile.devel/' .packit_rpm/mutter.spec"
        - rm -fv .packit_rpm/sources
    specfile_path: .packit_rpm/mutter.spec
jobs:
  - job: copr_build
    trigger: pull_request
    branch: gnome-48-mobile
    packages:
      - gnome-48-mobile
    additional_repos:
      - copr://@mobility/gnome-mobile
    targets:
      - fedora-42-x86_64
  - job: copr_build
    trigger: commit
    branch: gnome-48-mobile
    packages:
      - gnome-48-mobile
    owner: "@mobility"
    project: gnome-mobile
    targets:
      - fedora-42-aarch64
      - fedora-42-x86_64
      - fedora-rawhide-aarch64
      - fedora-rawhide-x86_64
  - job: copr_build
    trigger: pull_request
    branch: mobile
    packages:
      - mobile-devel
    additional_repos:
      - copr://@mobility/gnome-mobile
    targets:
      - fedora-rawhide-x86_64
  - job: copr_build
    trigger: commit
    branch: mobile
    packages:
      - mobile-devel
    owner: "@mobility"
    project: gnome-mobile
    targets:
      - fedora-42-aarch64
      - fedora-42-x86_64
      - fedora-rawhide-aarch64
      - fedora-rawhide-x86_64
